name: Post message to ONCE Campfire chat instance
description: Get notified of GitHub events by posting messages to a ONCE Campfire chat instance
author: Shane Lamb
inputs:
  messages_url:
    description: 'Bot URL to post message to room. Format: https://YOUR_DOMAIN/rooms/ROOM_NUMBER/BOT_KEY/messages'
    required: true
  topic:
    description: 'Type of content to include in the message. Options: commit_info, custom'
    required: true
    default: commit_info

runs:
  using: node20
  main: dist/index.js
