name: Post message to Campfire
description: Notifies of GitHub events by posting messages to a ONCE Campfire chat instance via bot account
author: Shane Lamb
inputs:
  messages_url:
    description: 'Bot URL to post message to room. Format: https://YOUR_DOMAIN/rooms/ROOM_NUMBER/BOT_KEY/messages'
    required: true
  template:
    description: 'Defines the event context/content of the post. Options: commit_pushed, job_failed'
    required: true

runs:
  using: node20
  main: dist/index.js
